.\"/*
.\" * Copyright (c) 2008 Red Hat, Inc.
.\" *
.\" * All rights reserved.
.\" *
.\" * Author: Christine Caulfield <ccaulfie@redhat.com>
.\" *
.\" * This software licensed under BSD license, the text of which follows:
.\" *
.\" * Redistribution and use in source and binary forms, with or without
.\" * modification, are permitted provided that the following conditions are met:
.\" *
.\" * - Redistributions of source code must retain the above copyright notice,
.\" *   this list of conditions and the following disclaimer.
.\" * - Redistributions in binary form must reproduce the above copyright notice,
.\" *   this list of conditions and the following disclaimer in the documentation
.\" *   and/or other materials provided with the distribution.
.\" * - Neither the name of the MontaVista Software, Inc. nor the names of its
.\" *   contributors may be used to endorse or promote products derived from this
.\" *   software without specific prior written permission.
.\" *
.\" * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
.\" * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
.\" * THE POSSIBILITY OF SUCH DAMAGE.
.\" */
.TH VOTEQUORUM_OVERVIEW 8 2009-01-26 "corosync Man Page" "Corosync Cluster Engine Programmer's Manual"
.SH NAME
votequorum_overview \- Votequorum Library Overview
.SH OVERVIEW
The votequuorum library is delivered with the corosync project. It is the external interface to
the vote-based quorum service. This service is optionally loaded into all ndes in a corosync cluster
to avoid split-brain situations. It does this by having a number of votes assigned to each system
in the cluster and ensuring that only when a majority of the votes are present, cluster operations are
allowed to proceed.
.PP
The library provides a mechanism to:
.PP
* Query the quorum status
.PP
* Get a list of nodes known to the quorum service
.PP
* Receive notifications of quorum state changes
.PP
* Change the number of votes assigned to a node
.PP
* Change the number of expected votes for a cluster to be quorate
.PP
* Connect an additional quorum device to allow small clusters to remain quorate during node outages.
.PP
.B votequorum
reads its configuration from the objdb. The following keys are read when it starts up:
.PP
* quorum.expected_votes
.br
* quorum.votes
.br
* quorum.quorumdev_poll
.br
* quorum.disallowed
.br
* quorum.two_node
.PP
Most of those values can be changed while corosync is running with the following exceptions:
.B quorum.disallowed
cannot be changed, and
.B two_node
cannot be set on-the-fly, though it can be cleared. ie you can start with two nodes in the cluster
and add a third without rebooting all the nodes.
.PP
.SH BUGS
This software is not yet production, so there may still be some bugs.
.SH "SEE ALSO"
.BR corosync-quorumtool (8),
.BR votequorum_initialize (3),
.BR votequorum_finalize (3),
.BR votequorum_fd_get (3),
.BR votequorum_dispatch (3),
.BR votequorum_context_get (3),
.BR votequorum_context_set (3),
.PP
