#!/bin/sh
# Copyright (c) 2005 MontaVista Software, Inc.
# 
# All rights reserved.
# 
# This software licensed under BSD license, the text of which follows:
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# - Neither the name of the MontaVista Software, Inc. nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.

# This script will instantiate, terminate, or cleanup using default actions
# It may be modified to do any action desired.

instantiate() {
#	echo clc_cli_script instantiating component $SA_AMF_COMPONENT_NAME $1
	./openais-instantiate $1
	exit $?
}

terminate() {
	if [ -w /var/run ]; then
		PIDFILEPATH=/var/run
	else
		PIDFILEPATH=/tmp
	fi
	echo clc_cli_script terminating component $SA_AMF_COMPONENT_NAME on PID \
	`cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
	kill -15 `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
	exit $?
}

cleanup() {
	if [ -w /var/run ]; then
		PIDFILEPATH=/var/run
	else
		PIDFILEPATH=/tmp
	fi
#	echo clc_cli_script cleaning up component $SA_AMF_COMPONENT_NAME on PID \
#	`cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
	kill -9 `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
	STATUS=$?
	if [ $STATUS == 1 ]; then
		exit 0
	else
		exit $STATUS
	fi
}

usage() {
		echo $"Usage: $0 {instantiate|terminate|cleanup}"
}

case "$1" in
	instantiate)
		if [ $# -gt 1 ]; then
			instantiate $2
		else 
			instantiate $COMP_BINARY_PATH/$COMP_BINARY_NAME
		fi
		;;

	terminate)
		terminate
		;;

	cleanup)
		cleanup
		;;

	*)
		usage
		exit 1

esac
exit 0
