/*
 * Copyright (c) 2002-2005 MontaVista Software, Inc.
 *
 * All rights reserved.
 *
 * Author: Steven Dake (sdake@mvista.com)
 *
 * This software licensed under BSD license, the text of which follows:
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - Neither the name of the MontaVista Software, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef IPC_GEN_H_DEFINED
#define IPC_GEN_H_DEFINED

enum req_init_types {
	MESSAGE_REQ_EVS_INIT,
	MESSAGE_REQ_CLM_INIT,
	MESSAGE_REQ_AMF_INIT,
	MESSAGE_REQ_CKPT_INIT,
	MESSAGE_REQ_CKPT_CHECKPOINT_INIT,
	MESSAGE_REQ_CKPT_SECTIONITERATOR_INIT,
	MESSAGE_REQ_EVT_INIT
};

enum res_init_types {
	MESSAGE_RES_INIT
};

#define	MESSAGE_REQ_LIB_ACTIVATEPOLL 0
#define	MESSAGE_RES_LIB_ACTIVATEPOLL 50

enum nodeexec_message_types {
	MESSAGE_REQ_EXEC_EVS_MCAST,
	MESSAGE_REQ_EXEC_CLM_NODEJOIN,
	MESSAGE_REQ_EXEC_AMF_COMPONENTREGISTER,
	MESSAGE_REQ_EXEC_AMF_COMPONENTUNREGISTER,
	MESSAGE_REQ_EXEC_AMF_ERRORREPORT,
	MESSAGE_REQ_EXEC_AMF_ERRORCANCELALL,
	MESSAGE_REQ_EXEC_AMF_READINESSSTATESET,
	MESSAGE_REQ_EXEC_AMF_HASTATESET,
	MESSAGE_REQ_EXEC_CKPT_CHECKPOINTOPEN,
	MESSAGE_REQ_EXEC_CKPT_CHECKPOINTCLOSE,
	MESSAGE_REQ_EXEC_CKPT_CHECKPOINTUNLINK,
	MESSAGE_REQ_EXEC_CKPT_CHECKPOINTRETENTIONDURATIONSET,
	MESSAGE_REQ_EXEC_CKPT_CHECKPOINTRETENTIONDURATIONEXPIRE,
	MESSAGE_REQ_EXEC_CKPT_SECTIONCREATE,
	MESSAGE_REQ_EXEC_CKPT_SECTIONDELETE,
	MESSAGE_REQ_EXEC_CKPT_SECTIONEXPIRATIONTIMESET,
	MESSAGE_REQ_EXEC_CKPT_SECTIONWRITE,
	MESSAGE_REQ_EXEC_CKPT_SECTIONOVERWRITE,
	MESSAGE_REQ_EXEC_CKPT_SECTIONREAD,
	MESSAGE_REQ_EXEC_EVT_EVENTDATA,
	MESSAGE_REQ_EXEC_EVT_CHANCMD,
	MESSAGE_REQ_EXEC_EVT_RECOVERY_EVENTDATA
};

#endif /* IPC_GEN_H_DEFINED */
